version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.13
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest tests/ -v -s
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN
      
      - run:
          name: Run hw3 github module (optional - requires GITHUB_TOKEN)
          command: |
            . venv/bin/activate
            python hw3/app.py || echo "Skipping GitHub API calls - no token provided"
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN

workflows:
  version: 2
  test:
    jobs:
      - build